// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USFTrading.DataAccess;

namespace USFTrading.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190422050659_IntialCreated")]
    partial class IntialCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("USFTrading.Models.Company", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEO");

                    b.Property<string>("Gainer_Loser");

                    b.Property<string>("companyName");

                    b.Property<string>("description");

                    b.Property<string>("exchange");

                    b.Property<string>("industry");

                    b.Property<string>("sector");

                    b.HasKey("symbol");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("USFTrading.Models.KeyStatGainers", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("marketcap");

                    b.Property<float>("peRatio");

                    b.Property<float>("ttmDividendRate");

                    b.Property<float>("ttmEPS");

                    b.Property<float>("week52change");

                    b.Property<float>("week52high");

                    b.Property<float>("week52low");

                    b.HasKey("symbol");

                    b.ToTable("KeyStatGainers");
                });

            modelBuilder.Entity("USFTrading.Models.KeyStatLosers", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("marketcap");

                    b.Property<float>("peRatio");

                    b.Property<float>("ttmDividendRate");

                    b.Property<float>("ttmEPS");

                    b.Property<float>("week52change");

                    b.Property<float>("week52high");

                    b.Property<float>("week52low");

                    b.HasKey("symbol");

                    b.ToTable("KeyStatLosers");
                });

            modelBuilder.Entity("USFTrading.Models.Sectors", b =>
                {
                    b.Property<string>("name")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("lastUpdated");

                    b.Property<float>("performance");

                    b.Property<string>("type");

                    b.HasKey("name");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("USFTrading.Models.Stock", b =>
                {
                    b.Property<string>("symbol")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("change");

                    b.Property<float>("changePercent");

                    b.Property<float>("close");

                    b.Property<float>("marketCap");

                    b.Property<float>("previousClose");

                    b.HasKey("symbol");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
